"""rename var to now_playing

Revision ID: 490a1d425b47
Revises: e3f6d0a9993f
Create Date: 2025-11-23 06:01:32.565198

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '490a1d425b47'
down_revision = 'e3f6d0a9993f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('now_playing', sa.String(length=64), nullable=True))
        batch_op.drop_column('current_track')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_track', mysql.VARCHAR(length=64), nullable=True))
        batch_op.drop_column('now_playing')

    # ### end Alembic commands ###
