"""add queue active device column

Revision ID: 6c7de4be71a2
Revises: a1d7b2e393ed
Create Date: 2025-09-30 10:11:30.124445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c7de4be71a2'
down_revision = 'a1d7b2e393ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_device', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queue', schema=None) as batch_op:
        batch_op.drop_column('active_device')

    # ### end Alembic commands ###
