"""update queue model

Revision ID: b29e1cb80d89
Revises: 6c7de4be71a2
Create Date: 2025-11-18 13:52:16.683618

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b29e1cb80d89'
down_revision = '6c7de4be71a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queues',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('active_device', sa.String(length=64), nullable=True),
    sa.Column('current_track', sa.String(length=64), nullable=True),
    sa.Column('progress_ms', sa.Integer(), nullable=True),
    sa.Column('tracks', sa.JSON(), nullable=True),
    sa.Column('users', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('track',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('artists', sa.String(length=64), nullable=True),
    sa.Column('duration_ms', sa.String(length=64), nullable=True),
    sa.Column('images', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('queue')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.create_table('queue',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('current_track', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('tracks', mysql.JSON(), nullable=True),
    sa.Column('users', mysql.JSON(), nullable=True),
    sa.Column('active_device', mysql.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('track')
    op.drop_table('queues')
    # ### end Alembic commands ###
