"""migrate to latest

Revision ID: b9b70e90ffa6
Revises: b9cf83922cfc
Create Date: 2025-12-29 12:11:40.314639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9b70e90ffa6'
down_revision = 'b9cf83922cfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queues',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('active_device', sa.String(length=64), nullable=True),
    sa.Column('now_playing', sa.String(length=64), nullable=True),
    sa.Column('progress_ms', sa.Integer(), nullable=True),
    sa.Column('tracks', sa.JSON(), nullable=True),
    sa.Column('users', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tracks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('artists', sa.String(length=64), nullable=True),
    sa.Column('duration_ms', sa.String(length=64), nullable=True),
    sa.Column('images', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(length=512), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('refresh_token', sa.String(length=512), nullable=False),
    sa.Column('user_role', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_user_id'))

    op.drop_table('users')
    op.drop_table('tracks')
    op.drop_table('queues')
    # ### end Alembic commands ###
