"""add user_role attribute

Revision ID: b9cf83922cfc
Revises: 490a1d425b47
Create Date: 2025-11-28 10:46:43.194492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9cf83922cfc'
down_revision = '490a1d425b47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_role', sa.String(length=32), nullable=False))
        batch_op.drop_index(batch_op.f('user_id'))
        batch_op.create_index(batch_op.f('ix_users_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_user_id'))
        batch_op.create_index(batch_op.f('user_id'), ['user_id'], unique=True)
        batch_op.drop_column('user_role')

    # ### end Alembic commands ###
